version: '3'
services:
    base:
      build:
        context: .
        dockerfile: ./env/docker/base/Dockerfile
      command: "sleep 0"
    nginx:
        build:
          context: .
          dockerfile: ./env/docker/nginx/Dockerfile
        restart: always
        ports:
        - "20001:80"
        volumes:
          - ./src:/app:delegated
          - ./env/docker/nginx/conf.d:/etc/nginx/conf.d
        links:
          - php
    php:
        build:
          context: .
          dockerfile: ./env/docker/php-fpm/Dockerfile
          args:
            BUILD_ENV: local
        restart: always
        volumes:
          - ./src:/app:delegated
    codebuild:
        image: amazonlinux
        volumes:
          - ./codebuild:/codebuild
          - ./codedeploy:/codedeploy
          - ./:/src
        command: "sleep 10000000000"
        environment:
          - CODEBUILD_RESOLVED_SOURCE_VERSION=feefc35480f01d6612913daa9ea6229d26516b74
