#!/bin/bash

set -e
if [ ! -d "vendor" ]
then
	echo "Install dependencies by composer install"
	composer install
fi

if [ ! -f ".env" ]
then
	echo "Create env file and run create key"
	cp .env.example .env
	php artisan key:generate 
fi

echo "Clear cache configuration"
php artisan config:clear

echo "Configuration Caching"
php artisan config:cache

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
